### ISSUE TITLE
/perms listgroups - Error and server crash

### ISSUE THREAD

**Issue by catthou** [IsaiahMC/CyberPermissions#3]
I encounter this error and server crash when using CyberPermissions 1.4 on a 1.19.0 server.
```
[Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: me/isaiah/lib/IText
	at me.isaiah.mods.permissions.Fabric18Text.colored_literal(Fabric18Text.java:16) ~[CyberPermissions-1.4.jar:?]
	at me.isaiah.mods.permissions.commands.PermsCommand.colored_literal(PermsCommand.java:272) ~[CyberPermissions-1.4.jar:?]
	at me.isaiah.mods.permissions.commands.PermsCommand.sendMessage(PermsCommand.java:279) ~[CyberPermissions-1.4.jar:?]
	at me.isaiah.mods.permissions.commands.PermsCommand.run(PermsCommand.java:161) ~[CyberPermissions-1.4.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.class_2170.redirect$zzk000$performCommand(class_2170.java:547) ~[server-intermediary.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:261) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_43667(class_3244.java:1274) ~[server-intermediary.jar:?]
	at net.minecraft.class_7472.method_43897(class_7472.java:37) ~[server-intermediary.jar:?]
	at net.minecraft.class_7472.method_11054(class_7472.java:13) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:160) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: me.isaiah.lib.IText
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 24 more
```

Mods loaded:
```
Architectury
CyberPermissions
Dynmap
Fabric API
Lithium
MiniHUD
Phosphor
REI
ServerCore
WorldEdit
```

**Comment by isaiahpatton** [comment]
should be fixed now.
